default_language_version:
    python: python3.8
default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v1.5'  # Use the sha / tag you want to point at
    hooks:
    -   id: autopep8
-   repo: https://github.com/mverteuil/precommit-dephell
    rev: master
    hooks:
        - id: pyproject-toml-to-setup-py
        - id: pyproject-toml-to-requirements-txt
-   repo: https://github.com/Woile/commitizen
    rev: v1.16.2
    hooks:
      - id: commitizen
        stages: [commit-msg]